### ISSUE TITLE
Files Disappearing in One Pod with subPath Mounting on Shared PVC/PV, but Visible in MinIO and Other Pods

### ISSUE THREAD

**Issue by guqiu369** [yandex-cloud/geesefs#123]
We are using multiple pods to access the same PVC/PV with subPath mounting. During usage, we noticed that in one of the pods, after creating a new file in the subPath mount, the file is initially visible when using the ls command, but after a while, the file disappears from the ls output. However, when we check the corresponding path in the bucket using MinIO's web service or the MinIO pod node, the newly created file is still present.

Additionally, we created other pods that use subPath to mount the same directory and scheduled them on the same Kubernetes node as the problematic pod. In the new pod, after creating new files, the files are visible both in the new pod and in MinIO, and the new pod can also see the files that were previously created in the problematic pod and later disappeared. However, these files remain invisible in the problematic pod.

On the host machine, we can see the relevant mount information using the mount -l command. The issue seems to be related to geesefs. We are looking for help from the community to resolve this issue.

**Comment by vitalif** [comment]
Hi, it's hard to debug such problems without details, so please reproduce it and provide a debug log of the problematic pod. It will help to identify your issue.

**Comment by washcycle** [comment]
I ran into this issue today.

```bash
[csi-s3-6mr7w/csi-s3]I0624 11:37:11.635271       1 mounter.go:65] Mounting fuse with command: geesefs and args: [--endpoint http://apqx-vast-s3.tailscale.svc.cluster.local -o allow_other --log-file /dev/stderr --setuid 65534 --setgid 65534 --memory-limit 1000 --dir-mode 0777 --file-mode 0666 --debug_s3 --debug_fuse apqx-data: /var/lib/kubelet/plugins/kubernetes.io/csi/ru.yandex.s3.csi/b722acf6d93baae95e86e8785caa76b15ea807868c5d5a520bfcf4dacc7c51af/globalmount]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692366 s3.DEBUG HEAD http://apqx-vast-s3.tailscale.svc.cluster.local/apqx-data = 403 []
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692402 s3.DEBUG X-Amz-Request-Id = [16910100000151]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692407 s3.DEBUG Date = [Tue, 24 Jun 2025 11:35:13 GMT]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692410 s3.DEBUG Strict-Transport-Security = [max-age=86400]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692413 s3.DEBUG X-Content-Type-Options = [nosniff]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692416 s3.DEBUG X-Frame-Options = [SAMEORIGIN]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692418 s3.DEBUG Content-Length = [0]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692422 s3.DEBUG Server = [vast 5.1.0.251]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692424 s3.DEBUG X-Amz-Id-2 = [16910100000151]
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.692671 s3.DEBUG DEBUG: Request s3/HeadObject Details:
[csi-s3-6mr7w/csi-s3]---[ REQUEST POST-SIGN ]-----------------------------
[csi-s3-6mr7w/csi-s3]HEAD /apqx-data/t07tqiexq4aaxf5x94n4ncxnci69neeb HTTP/1.1
[csi-s3-6mr7w/csi-s3]Host: apqx-vast-s3.tailscale.svc.cluster.local
[csi-s3-6mr7w/csi-s3]User-Agent: GeeseFS/0.43.0 (go1.22.12; linux; amd64)
[csi-s3-6mr7w/csi-s3]Authorization: AWS4-HMAC-SHA256 Credential=xxxxxxxxxxxx/20250624/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=xxxxxxxx
[csi-s3-6mr7w/csi-s3]X-Amz-Content-Sha256: xxxxx
[csi-s3-6mr7w/csi-s3]X-Amz-Date: 20250624T113711Z
[csi-s3-6mr7w/csi-s3]
[csi-s3-6mr7w/csi-s3]
[csi-s3-6mr7w/csi-s3]-----------------------------------------------------
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.697275 s3.DEBUG DEBUG: Response s3/HeadObject Details:
[csi-s3-6mr7w/csi-s3]---[ RESPONSE ]--------------------------------------
[csi-s3-6mr7w/csi-s3]HTTP/1.1 404 Not Found
[csi-s3-6mr7w/csi-s3]Date: Tue, 24 Jun 2025 11:35:13 GMT
[csi-s3-6mr7w/csi-s3]Server: vast 5.1.0.251
[csi-s3-6mr7w/csi-s3]Strict-Transport-Security: max-age=86400
[csi-s3-6mr7w/csi-s3]X-Amz-Id-2: 16910100000152
[csi-s3-6mr7w/csi-s3]X-Amz-Request-Id: 16910100000152
[csi-s3-6mr7w/csi-s3]X-Content-Type-Options: nosniff
[csi-s3-6mr7w/csi-s3]X-Frame-Options: SAMEORIGIN
[csi-s3-6mr7w/csi-s3]Content-Length: 0
[csi-s3-6mr7w/csi-s3]
[csi-s3-6mr7w/csi-s3]
[csi-s3-6mr7w/csi-s3]-----------------------------------------------------
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.697299 s3.DEBUG DEBUG: Validate Response s3/HeadObject failed, attempt 0/3, error NotFound: Not Found
[csi-s3-6mr7w/csi-s3]	status code: 404, request id: 16910100000152, host id: 16910100000152
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.697474 s3.DEBUG DEBUG: Request s3/ListMultipartUploads Details:
[csi-s3-6mr7w/csi-s3]---[ REQUEST POST-SIGN ]-----------------------------
[csi-s3-6mr7w/csi-s3]GET /apqx-data?uploads= HTTP/1.1
[csi-s3-6mr7w/csi-s3]Host: apqx-vast-s3.tailscale.svc.cluster.local
[csi-s3-6mr7w/csi-s3]User-Agent: GeeseFS/0.43.0 (go1.22.12; linux; amd64)
[csi-s3-6mr7w/csi-s3]Accept-Encoding: identity
[csi-s3-6mr7w/csi-s3]Authorization: AWS4-HMAC-SHA256 Credential=xxxxxxxxxx/20250624/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=xxxxxxx
[csi-s3-6mr7w/csi-s3]X-Amz-Content-Sha256: xxxxx
[csi-s3-6mr7w/csi-s3]X-Amz-Date: 20250624T113711Z
[csi-s3-6mr7w/csi-s3]
[csi-s3-6mr7w/csi-s3]`
[csi-s3-6mr7w/csi-s3]-----------------------------------------------------
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.703473 s3.DEBUG DEBUG: Response s3/ListMultipartUploads Details:
[csi-s3-6mr7w/csi-s3]---[ RESPONSE ]--------------------------------------
[csi-s3-6mr7w/csi-s3]HTTP/1.1 200 OK
[csi-s3-6mr7w/csi-s3]Transfer-Encoding: chunked
[csi-s3-6mr7w/csi-s3]Date: Tue, 24 Jun 2025 11:35:13 GMT
[csi-s3-6mr7w/csi-s3]Server: vast 5.1.0.251
[csi-s3-6mr7w/csi-s3]Strict-Transport-Security: max-age=86400
[csi-s3-6mr7w/csi-s3]X-Amz-Id-2: 16910100000153
[csi-s3-6mr7w/csi-s3]X-Amz-Request-Id: 16910100000153
[csi-s3-6mr7w/csi-s3]X-Content-Type-Options: nosniff
[csi-s3-6mr7w/csi-s3]X-Frame-Options: SAMEORIGIN
[csi-s3-6mr7w/csi-s3]
[csi-s3-6mr7w/csi-s3]
[csi-s3-6mr7w/csi-s3]-----------------------------------------------------
[csi-s3-6mr7w/csi-s3]2025/06/24 11:37:11.703520 s3.DEBUG {
[csi-s3-6mr7w/csi-s3]  Bucket: "apqx-data",
[csi-s3-6mr7w/csi-s3]  IsTruncated: false,
[csi-s3-6mr7w/csi-s3]  KeyMarker: "",
[csi-s3-6mr7w/csi-s3]  MaxUploads: 1000,
[csi-s3-6mr7w/csi-s3]  NextKeyMarker: "",
[csi-s3-6mr7w/csi-s3]  NextUploadIdMarker: "",
[csi-s3-6mr7w/csi-s3]  UploadIdMarker: "0"
[csi-s3-6mr7w/csi-s3]}
```

```yaml
# The access modes much match between the PV and PVC.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apqx-vast-s3-static-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: apqx-vast-s3-static-pvc
  csi:
    driver: ru.yandex.s3.csi
    controllerPublishSecretRef:
      name: csi-vast-s3-secret-apqx
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-vast-s3-secret-apqx
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-vast-s3-secret-apqx
      namespace: kube-system
    volumeAttributes:
      capacity: 10Gi
      mounter: geesefs
      options: --no-systemd --memory-limit 1000 --dir-mode 0777 --file-mode 0666 --debug_s3 --debug_fuse
    volumeHandle: apqx-data # <--- your existing bucket name or bucket/path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apqx-vast-s3-static-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wf1-s3-pvc
  namespace: default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-s3-static-test
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "10m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      volumeMounts:
        - name: apqx-tools
          mountPath: /mnt/
          subPath: scratch
  volumes:
    - name: apqx-tools
      persistentVolumeClaim:
        claimName: apqx-vast-s3-static-pvc
```

Trying to turn things on and off to see if I can isolate any particular setting.

I am on AKS 1.33+ and I did disable systemmd, because I'm using a proxy for s3 storage inside the cluster, so I needed to resolve and connect to a cluster.local IP.

If I remove the subpath it works as expected and I can list all files and all operations work.
